# Generated by Django 5.0.6 on 2024-06-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='pavilhao',
            field=models.CharField(choices=[('1', 'Pavilhão 01'), ('2', 'Pavilhão 02')], max_length=1),
        ),
    ]
