# Generated by Django 5.0.6 on 2024-06-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_sala_pavilhao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocurso',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=5),
        ),
    ]
