# Generated by Django 5.0.6 on 2024-06-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_registrocurso_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtivarPesquisaSalas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativado', models.BooleanField(default=False)),
            ],
        ),
    ]
