# Generated by Django 5.0.6 on 2024-06-10 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_ativarpesquisasalas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[(1, 'Domingo'), (2, 'Segunda Feira'), (3, 'Terça Feira'), (4, 'Quarta Feira'), (5, 'Quinta Feira'), (6, 'Sexta Feira'), (7, 'Sábado')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrocurso',
            name='sala',
        ),
        migrations.CreateModel(
            name='CronogramaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.sala')),
                ('dias', models.ManyToManyField(to='usuario.dias')),
            ],
        ),
        migrations.AddField(
            model_name='registrocurso',
            name='sala',
            field=models.ManyToManyField(to='usuario.cronogramasala'),
        ),
    ]
