# Generated by Django 5.0.6 on 2024-06-11 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_dias_remove_registrocurso_sala_cronogramasala_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dias',
            name='dia',
            field=models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda Feira'), ('3', 'Terça Feira'), ('4', 'Quarta Feira'), ('5', 'Quinta Feira'), ('6', 'Sexta Feira'), ('7', 'Sábado')], max_length=1),
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.sala')),
            ],
        ),
    ]
