# Generated by Django 5.0.6 on 2024-06-11 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_dias_dia_contador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Relatório de Inserções',
                'verbose_name_plural': 'Relatórios de Inserções',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuario.contador',),
        ),
    ]
